---
site_name: "NAF Workshop WS:C4 - AutoCon2"
site_description: Leveraging Python Ecosystem for Quick CLI Tool Creation
nav:
  - FAQ: "index.md"
  - Agenda: "agenda.md"
  - Poetry: "poetry.md"
  - LAB Poetry: "lab_poetry.md"
  - Nornir: "nornir.md"
  - LAB Network API: "lab_network_api.md"
  - rich: rich.md
  - LAB rich: lab_rich.md
  - Pydantic: pydantic.md
  - LAB Pydantic: lab_pydantic.md
  - Typer: typer.md
  - CLI App: cli_app.md
  - Optional:
    - pipx: "pipx.md"
    - NAPALM Mock: napalm_mock.md
    - rich SVG: rich_svg.md
    - Pydantic: pydantic_plus.md
    - Testing Typer: testing_typer.md
    - Publish Package: publish_package.md



repo_url: https://github.com/ubaumann/naf_workshop_cli_tool
repo_name: ubaumann/naf_workshop_cli_tool

theme:
  name: material
  logo: img/NAF.png
  favicon: img/favicon.png
  palette:
    - scheme: slate
      primary: custom
      accent: custom
  features:
    - navigation.tracking
extra_css:
  - stylesheets/extra.css

plugins:
    - with-pdf:
        author: Urs Baumann
        copyright: ""
        #
        #cover: false
        #back_cover: true
        #cover_title: TITLE TEXT
        cover_subtitle: Leveraging Python Ecosystem for Quick CLI Tool Creation
        # custom_template_path: "stylesheets/pdf.css"
        #
        # toc_title: TOC TITLE TEXT
        #heading_shift: false
        #toc_level: 3
        #ordered_chapter_level: 2
        #excludes_children:
        #    - 'release-notes/:upgrading'
        #    - 'release-notes/:changelog'
        #
        #exclude_pages:
        #    - 'bugs/'
        #    - 'appendix/contribute/'
        #convert_iframe:
        #    - src: IFRAME SRC
        #      img: POSTER IMAGE URL
        #      text: ALTERNATE TEXT
        #    - src: ...
        #two_columns_level: 3
        #
        #render_js: true
        #headless_chrome_path: headless-chromium
        #
        output_path: workshop.pdf
        #enabled_if_env: ENABLE_PDF_EXPORT
        #
        # debug_html: true
        #show_anchors: true
        # verbose: true
